### ISSUE TITLE
站点支持https&http双tracker会导致重复添加任务

### ISSUE THREAD

**Issue by ashmodeus1986** [ledccn/IYUUAutoReseed#12]
不确定这是不是bug，leaguehd站实际使用中出现了几个任务重复添加了；添加完后两个任务都能连接tracker。

另外改进建议：
1、增加linux下执行命令说明到wiki；
2、脚本执行完增加成功输出，目前是靠微信统计报表消息发过来才确认执行完毕；
3、cache文件夹内会保存passkey，安全考虑建议删除；

**Comment by ledccn** [comment]
回复leaguehd重复问题：目前已知很多站有类似现象，原因是发布者重新制作种子造成的。（可以去站内看看，确实有多个重复种子）
回复3：cache文件夹保持passkey的问题下次更新时候处理。
