### ISSUE TITLE
能否增加对 rtorrent 的支持？

### ISSUE THREAD

**Issue by MeetWq** [ledccn/IYUUAutoReseed#14]
如题，我用的是 rtorrent + rutorrent

**Comment by maicss** [comment]
https://github.com/ledccn/IYUUAutoReseed/issues/28 提问题之前搜一下

**Comment by MeetWq** [comment]
> #28 提问题之前搜一下

但这是我先提的啊

**Comment by maicss** [comment]
哦，那……也关了吧
