### ISSUE TITLE
能否自动开始上传？

### ISSUE THREAD

**Issue by Se7enMuting** [ledccn/IYUUAutoReseed#16]
自动辅种添加种子，校验完成后，如果是100%的种子，能否自动开始上传？有什么办法可以实现吗？
我现在检验后的种子都是暂停状态，要手动进TR/qB里选种子按开始~~

**Comment by ledccn** [comment]
实践中发现很多种子被改过！为了账号安全，避免因校验失败下载不必要的文件，所以校验后的种子是暂停状态。

**Comment by Se7enMuting** [comment]
校验后是100%的种子都可能会有问题吗？
