### ISSUE TITLE
小小建议-自动删种子

### ISSUE THREAD

**Issue by lixiaolong2** [ledccn/IYUUAutoReseed#2]
现在支持部分站点自动下载免费种子，但是一旦多了就硬盘会爆炸。

可否支持下自动删种子功能呢。比如分享率在做种多少小时后还没达到就自动删，等等。

**Comment by ledccn** [comment]
收到反馈，功能在后续会逐步完善。

**Comment by ledccn** [comment]
后期其他的功能项里面，会做。
