### ISSUE TITLE
大佬，添加计划任务失败。

### ISSUE THREAD

**Issue by xywjlidi** [ledccn/IYUUAutoReseed#21]
WIN10添加了自动辅种的计划任务，但是一直提示“操作员或系统管理员拒绝了请求（0x800710E0）”。单独运行“9.执行辅种.cmd”，没有问题，可以辅种。

**Comment by ledccn** [comment]
添加win计划任务的话，复制一份脚本修改，1.需要使用绝对路径；2.去掉结尾的pause。
