### ISSUE TITLE
天雪skyey辅种问题

### ISSUE THREAD

**Issue by InDimension** [ledccn/IYUUAutoReseed#22]
配置天雪passkey后运行脚本没发现skyey的辅种过程，不知道是不是工具域名没更新的问题。
现在天雪域名为www.skyey2.com
对于skyey自动辅种支持的域名貌似还是www.skyeysnow.com

**Comment by Rhilip** [comment]
站点域名问题，现在可以通过 `url_replace` 配置项修改。
辅种不能，似乎是因为种子库没更新到，具体我再问问。

**Comment by ledccn** [comment]
> 配置天雪passkey后运行脚本没发现skyey的辅种过程，不知道是不是工具域名没更新的问题。
> 现在天雪域名为www.skyey2.com
> 对于skyey自动辅种支持的域名貌似还是www.skyeysnow.com

我这边经测试，2个域名都可以访问；不过，已把辅种域名变更为www.skyey2.com。因存在缓存，生效需要2小时左右。
经检查历史记录，天雪种子爬取还是比较正常的。

**Comment by InDimension** [comment]
我是在威联通nas上使用php进行运作的，
没有辅种的情况是和链接的issue情况类似，只是描述上他用的是GUI，
如果确认没有问题的话就close吧。
谢谢。
https://gitee.com/ledc/IYUUAutoReseed/issues/I1VBRN

**Comment by ledccn** [comment]
此外，我还发现天雪站修改框架时遗留的重大bug，问题描述：
在用户上传种子时，此站代码本应修改种子的info字段，却漏掉了此步骤，会导致种子的info哈希与源站一模一样，导致下载器无法同时做种。（也会导致tracker汇报问题，如流量作弊等）。
