### ISSUE TITLE
请问能否清理下无效种子

### ISSUE THREAD

**Issue by gitnoobbbb** [ledccn/IYUUAutoReseed#23]
首先感谢开发者无私付出,推出IYUU这一pt神器,挽救众多站点,同时也给个人用户带来更好的体验

但从各个站点爬取的种子有部分会被站点或者发布者删除...
随着时间推移,这种无效种子累积越来越多,在辅种过程中出现大量辅种失败的报告,有的甚至卡停很久,这降低了附种效率,也不利于查看结果...

所以个人建议:
是否能抽空清理下这种类型的种子,不知技术上能否简单实现...

请您酌情考虑,谢谢

**Comment by ledccn** [comment]
3个月积累两万多无效种子，目前已清理的剩下5000多个。
