### ISSUE TITLE
api提示用户未绑定合作站点账号

### ISSUE THREAD

**Issue by foxconndmd** [ledccn/IYUUAutoReseed#24]
通过[http://api.iyuu.cn/index.php?s=App.Api.Hash](http://api.iyuu.cn/index.php?s=App.Api.Hash)测试，使用[https://iyuu.cn/](https://iyuu.cn/)申请的token，提示以下错误：
```
{
    "ret": 401,
    "data": {},
    "msg": "非法请求：用户未绑定合作站点账号！请查阅绑定！https://www.iyuu.cn/archives/337/",
    "version": "1.9.1"
}
```

**Comment by Mokee-nmy** [comment]
Hi，您这个问题是如何解决的呢

**Comment by foxconndmd** [comment]
> 
> 
> Hi，您这个问题是如何解决的呢

没解决，当时兴起测试了下，后续没再使用，好像要通过授权站点认证吧，具体可以看看iyuu源码
