### ISSUE TITLE
希望可以增加添加种子tracker为https选项

### ISSUE THREAD

**Issue by Shouyupedia** [ledccn/IYUUAutoReseed#25]
目前遇到问题是mteam的自动添加的种子tracker为http，不能正常工作

**Comment by Rhilip** [comment]
https://github.com/ledccn/IYUUAutoReseed/blob/6eebc7d26cc064175aaeeb9713e9de7708152b2c/config/config.sample.php#L198-L208
请问你是对配置项做了什么手脚吗？
