### ISSUE TITLE
如何换绑微信账号？合作站点鉴权失败

### ISSUE THREAD

**Issue by qwsxmkoi** [ledccn/IYUUAutoReseed#27]
今天在群里遇到一个需要换绑微信的群友
以前没有合作站点鉴权的时候只需要重新生成一个令牌然后改config就行了
但是现在改了之后会导致合作站点鉴权失败，所以也就是断绝了更改绑定通知微信的可能
不知道能否开发一个解绑的功能？

**Comment by ledccn** [comment]
后面会考虑解绑操作。
