### ISSUE TITLE
建议增加rtorrent(rutorrent)客户端的支持

### ISSUE THREAD

**Issue by Ret70** [ledccn/IYUUAutoReseed#28]
保种的话，rtorrent（rutorrent）对设备要求最低，对资源占用也比较低，希望能支持。

**Comment by sonicLee** [comment]
因为pt站都把rtorrent做为banclient，所以支持上估计作者也不咋想支持吧

**Comment by MeetWq** [comment]
> 因为pt站都把rtorrent做为banclient，所以支持上估计作者也不咋想支持吧

我不知道哪些pt站不允许rtorrent，至少我有的站都是可以用rtorrent的

**Comment by mxx894** [comment]
同样   rtorrent对设备支持好 但设置复杂  、但用的人也不少   希望作者可以支持
