### ISSUE TITLE
建议修改hdu的tracker到支持双栈的那个

### ISSUE THREAD

**Issue by mayziran** [ledccn/IYUUAutoReseed#35]
hdu的tracker好像有两个，目前iyuu默认的好像是只支持ipv4的那个，pt助手默认添加的也是支持双栈的那个，建议修改。

**Comment by ledccn** [comment]
辅种脚本支持自定义参数，配置增加'url_join' => array(
            'ipv6=1',   // 种子Tracker的IP地址选择 可选：ipv4，ipv6
            'https=1',
        ),
