### ISSUE TITLE
辅种是按种子体积计算的么

### ISSUE THREAD

**Issue by lx354081082** [ledccn/IYUUAutoReseed#37]
![QQ图片20201217154810](https://user-images.githubusercontent.com/33972358/102458691-9634d080-407f-11eb-95af-417694ceff53.png)
本地只下了一个  自动辅了 好多个相同大小的种子

**Comment by iceyuamao0510** [comment]
这种都不算是issue，请直接到交流群问吧

**Comment by ledccn** [comment]
因为种子数据库比较大，单文件的可能会存在这种情况。
