### ISSUE TITLE
请求增加iyuu对华科蝴蝶的支持

### ISSUE THREAD

**Issue by bbpp222006** [ledccn/IYUUAutoReseed#39]
如题

**Comment by ledccn** [comment]
私聊我QQ吧

**Comment by GrayXu** [comment]
请问有进展嘛？

**Comment by shuosiw** [comment]
同问有进展么？

**Comment by GrayXu** [comment]
@ledccn Hi，我看到下游的[IYUUPlus](https://github.com/ledccn/IYUUPlus)已经更新支持蝴蝶了，上游这边什么时候更新呢？感谢

**Comment by ledccn** [comment]
上游什么时候更新，是什么意思？

**Comment by ledccn** [comment]
建议更新到IYUUPlus吧，同为php的CLI运行模式，但是增删改配置都在webui完成，很方便好用；是主要维护的版本；
感谢！

**Comment by GrayXu** [comment]
@ledccn 我发现增加下config就能用了，感谢。继续使用IYUUAutoReseed主要是因为我依赖于CLI环境了。  
另外我提了一个相关的pr。
