### ISSUE TITLE
建议添加对uTorrent支持

### ISSUE THREAD

**Issue by szRayX** [ledccn/IYUUAutoReseed#4]
很多站点推荐默认下载器是uTorrent 2.0.4，希望可以添加对uTorrent的支持。
非常感谢

**Comment by lysssssss** [comment]
大佬之前好像说过UT的API的问题，所以没法支持UT

**Comment by szRayX** [comment]
> 大佬之前好像说过UT的API的问题，所以没法支持UT

好像TJUPT大佬的reseed可以支持UT？

**Comment by lysssssss** [comment]
> > 大佬之前好像说过UT的API的问题，所以没法支持UT
> 
> 好像TJUPT大佬的reseed可以支持UT？

没用过reseed不清楚。
但应该是API里少了某些接口所以大佬放弃了吧，我不太记得他的原话了。ut是有api的但好像接口不全

**Comment by szRayX** [comment]
> > > 大佬之前好像说过UT的API的问题，所以没法支持UT
> > 
> > 
> > 好像TJUPT大佬的reseed可以支持UT？
> 
> 没用过reseed不清楚。
> 但应该是API里少了某些接口所以大佬放弃了吧，我不太记得他的原话了。ut是有api的但好像接口不全

瞎猜一个，调用ut 的web service推送下载好的torrent文件？PTPP好像可以实现推送torrent给ut的功能。

**Comment by EvineDeng** [comment]
reseed好像是只提供辅助的所有种子链接，使用qb或ut的批量下载种子功能后还得自己指定文件存放路径。
IYUUAutoReseed不需要你再指定辅种的文件路径，因为它直接从api读取到了你既有种子的存放路径。而UT的api根本就不提供文件存放路径，所以IYUUAutoReseed也就无法做到自动辅种。
个人认为IYUUAutoReseed这种直接读取既有种子的文件存放路径的方式要比reseed的方式人性化一些。

**Comment by ledccn** [comment]
uTorrent 2.0.4的API无法获取做种目录，支持的话也无法实现自动化辅种，所以暂时搁置了。
