### ISSUE TITLE
SQL Error Table 'nexusphp.torrents_' doesn't exist @ lemonhd / leaguehd

### ISSUE THREAD

**Issue by skygunner** [ledccn/IYUUAutoReseed#43]
尝试用IYUU Gui辅种，但是这个站点完全无法添加，全部添加种子失败，Gui让尝试手动添加种子，
但是点击Gui给出的种子链接，则会报这个错误：

SQL Error
Table 'nexusphp.torrents_' doesn't exist
in /home/wwwroot/leaguehd.com/download.php, line 80

是不是因为该站点魔改了？

**Comment by skygunner** [comment]
比如点击  https://lemonhd.org/download.php?id=73870&passkey=my-passkey-removed

**Comment by ledccn** [comment]
感谢反馈，Gui版本Issues统一在这里提交反馈：https://github.com/Rhilip/IYUU-GUI/issues
