### ISSUE TITLE
关于iyuu对于定义的多个辅种客户端支持的优化建议

### ISSUE THREAD

**Issue by zhufeng** [ledccn/IYUUAutoReseed#47]
1、目前的版本里面，如果我在config.php里面定义了多个下载器，只要其中有任意一个下载器webui无法连接，则所有定义的下载器都不会去连接，会在初始化的时候直接报错，其它所有的下载器都不会尝试发起辅种。

比如我有多个下载器，其中某一台只在特定的时间打开，这样就会影响到其它下载器的辅种。

能否使用循环遍历所有定义的下载器，对于无法连接的下载器自动跳过呢，只有在所有定义的下载器都无法连接时才报错？

```| 51. dragonhd   | 52. hitpt     | 53. pttime  | 54. hdai        |
+----------------+---------------+-------------+-----------------+--------------+
transmission 客户端正在实例化！
transmission：http://127.0.0.1:****/transmission/rpc Rpc连接 [success]
qBittorrent 客户端正在实例化！
qBittorrent：https://127.0.0.1:**** Rpc连接 [v4.2.5]
qBittorrent 客户端正在实例化！
qBittorrent：https://127.0.0.1:**** Rpc连接 [v4.3.2]
qBittorrent 客户端正在实例化！
[连接错误] https://127.0.0.1:**** qBittorrent Unable to authenticate with Web Api.
```

2、目前的版本在config.php定义了多个辅种下载器时，在运行时打印的日志里面只会显示client 0， client 1这样，是否能在config.php里面定义一个下载器别名，然后在打印日志里面打印出别名或webui地址？

**Comment by ledccn** [comment]
新版已经有这个功能啦。

**Comment by zhufeng** [comment]
> 
> 
> 新版已经有这个功能啦。

更新到github里面的最新的commit版本，应该是22吧，貌似没有解决这个问题呢。
