### ISSUE TITLE
代码结构优化建议

### ISSUE THREAD

**Issue by Rhilip** [ledccn/IYUUAutoReseed#7]
- [x] 将原先的下载免费种子剥离出来，只做自动辅种。下载免费种涉及到网页爬虫，用户设置不当很容易被网站封号，**甚至连带开发者。**
- [x] 源代码中去除 `vendor` 目录，在release中添加自定义文件的形式给用户分发带有vendor的文件。
- [x] 自动加载优化，使用composer中的autoload -> psr-4 , classmap , file 配置项进行 Class、Protocols的加载，弃用以下inclue语句
https://github.com/ledccn/IYUUAutoReseed/blob/6216f8d5f3acf9fe14d7758da4e942727d8b27bf/app/init.php#L43-L58
- [ ] 增加bittorrent client的接口类，Tr、qB、uT等客户端在实现(implements)接口类的基础上进行开发。
- [ ] wiki直接放入Github提供的功能中

**Comment by ledccn** [comment]
3项已搞定。

**Comment by ledccn** [comment]
3项已搞定。
