### ISSUE TITLE
群晖运行时报错

### ISSUE THREAD

**Issue by tanpengsccd** [ledccn/IYUUAutoReseed#9]
```

root@DSMMSI:/volume3/homes/admin/IYUUAutoReseed# php ./iyuu.php
1580814946.6314 环境变量初始化完成！
1580814946.6315 全局配置载入完成！
PHP Warning:  require_once(/volume3/homes/admin/IYUUAutoReseed/vendor/autoload.php): failed to open stream: No such file or directory in /volume3/homes/admin/IYUUAutoReseed/init.php on line 47

Warning: require_once(/volume3/homes/admin/IYUUAutoReseed/vendor/autoload.php): failed to open stream: No such file or directory in /volume3/homes/admin/IYUUAutoReseed/init.php on line 47
PHP Fatal error:  require_once(): Failed opening required '/volume3/homes/admin/IYUUAutoReseed/vendor/autoload.php' (include_path='.') in /volume3/homes/admin/IYUUAutoReseed/init.php on line 47

Fatal error: require_once(): Failed opening required '/volume3/homes/admin/IYUUAutoReseed/vendor/autoload.php' (include_path='.') in /volume3/homes/admin/IYUUAutoReseed/init.php on line 47
```

**Comment by tanpengsccd** [comment]
我是git clone 下来的。

**Comment by tanpengsccd** [comment]
找到群里的vendor 文件了，解决

**Comment by ledccn** [comment]
缺少依赖包，用composer install安装一下即可。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tanpengsccd"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月4日(星期二) 晚上7:17
收件人:&nbsp;"ledccn/IYUUAutoReseed"<IYUUAutoReseed@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ledccn/IYUUAutoReseed] 群晖运行时报错 (#9)



root@DSMMSI:/volume3/homes/admin/IYUUAutoReseed# php ./iyuu.php /volume3/homes/admin/IYUUAutoReseed/init.phproot@DSMMSI:/volume3/homes/admin/IYUUAutoReseed# php ./iyuu.php 1580815026.3162 环境变量初始化完成！ 1580815026.3164 全局配置载入完成！ PHP Warning:  require_once(/volume3/homes/admin/IYUUAutoReseed/vendor/autoload.php): failed to open stream: No such file or directory in /volume3/homes/admin/IYUUAutoReseed/init.php on line 47 Warning: require_once(/volume3/homes/admin/IYUUAutoReseed/vendor/autoload.php): failed to open stream: No such file or directory in /volume3/homes/admin/IYUUAutoReseed/init.php on line 47 PHP Fatal error:  require_once(): Failed opening required '/volume3/homes/admin/IYUUAutoReseed/vendor/autoload.php' (include_path='.') in /volume3/homes/admin/IYUUAutoReseed/init.php on line 47 Fatal error: require_once(): Failed opening required '/volume3/homes/admin/IYUUAutoReseed/vendor/autoload.php' (include_path='.') in /volume3/homes/admin/IYUUAutoReseed/init.php on line 47
